name: tentacle_response_formatter
version: 0.1.0
description: Simple extensible response formatter which detects appropriate response format and serializes data accordingly.
homepage: https://github.com/octobyte/tentacle_response_formatter
author: Thomas Profelt <tom@octobyte.at>

dependencies:
  shelf: ">=0.5.0+1 <0.6.0"
  xml: ">=1.0.0 <2.0.0"

dev_dependencies:
  unittest: any

environment:
  sdk: ">=1.3.0"