name: tentacle_response_formatter
version: 0.1.0
description: Simple extensible response formatter which detects appropriate response format and serializes data accordingly.
homepage: https://github.com/octobyte/tentacle_response_formatter
author: Thomas Profelt <tom@octobyte.at>

dependencies:
  shelf: ">=0.6.0 <0.7.0"
  xml: ">=2.1.0 <3.0.0"

dev_dependencies:
  unittest: ">=0.9.0 <0.12.0"

environment:
  sdk: ">=1.3.0"
